import { Josefin_Sans} from "next/font/google";
import "./globals.css";



const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  display: "swap",
})

export const metadata = {
  title: "To-do-list",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} `}
      >
        {children}
      </body>
    </html>
  );
}
